// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctmzlorgzptgeluwjxwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0bXpsb3JnenB0Z2VsdXdqeHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTMyNzcsImV4cCI6MjA3MzQ4OTI3N30.sSt9h440CZ6aYyCdkALmGO5WEwL1z-6BBrnZeTJNkTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});